name: meal_nudge
description: "A Diet project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  mobile_scanner: ^6.0.0
  image_picker: ^1.1.2
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^18.0.0
  health: ^12.0.0
  timezone: ^0.9.0
  flutter_timezone: ^5.0.0
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3
  firebase_ai: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
